---
timeout: 1800s
options:
  env:
    - 'VENV=/workspace/venv'
steps:
  # Create virtualenv
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        pip install virtualenv==16.7.9
        virtualenv -p python3 "$$VENV"
        source "$$VENV"/bin/activate
        pip install twine

  # Build package
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        source "$$VENV"/bin/activate
        python setup.py sdist bdist_wheel

  # Test build output
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        source "$$VENV"/bin/activate
        twine check dist/*

  # Publish package
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        USERNAME=$(gcloud secrets versions access latest --secret="$PROJECT_ID"-username)
        PASSWORD=$(gcloud secrets versions access latest --secret="$PROJECT_ID"-password)
        if [ "$BRANCH_NAME" == "develop" ]; then
            REPO=testpypi
        else
            REPO=pypi
        fi
        source "$$VENV"/bin/activate
        twine upload -r "$$REPO" dist/* -u "$$USERNAME" -p "$$PASSWORD"
